- lib/src/flowcontrol/stream_queues.dart
- lib/src/streams/stream_handler.dart
- lib/transport.dart
- test/src/streams/streams_test.dart
This is needed for at least the Go gRPC client, which expects the
trailer frame to be sent with endStream==true.
> Allow closing the stream with the last frame.

- lib/src/artificial_server_socket.dart
- manual_test/out_of_stream_ids_test.dart
- test/client_test.dart
- test/multiprotocol_server_test.dart
- test/src/async_utils/async_utils_test.dart
- test/src/connection_preface_test.dart
- test/src/error_matchers.dart
- test/src/flowcontrol/connection_queues_test.dart
- test/src/flowcontrol/stream_queues_test.dart
- test/src/flowcontrol/window_handler_test.dart
- test/src/frames/frame_defragmenter_test.dart
- test/src/frames/frame_reader_test.dart
- test/src/frames/frame_writer_reader_test.dart
- test/src/frames/frame_writer_test.dart
- test/src/hpack/hpack_test.dart
- test/src/hpack/huffman_table_test.dart
- test/src/mock_utils.dart
- test/src/ping/ping_handler_test.dart
- test/src/settings/settings_handler_test.dart
- test/src/streams/helper.dart
- test/src/streams/simple_flow_test.dart
- test/src/streams/simple_push_test.dart
- test/src/streams/streams_test.dart
- test/transport_test.dart
Mostly updating tests to no longer use deprecated methods. After this,
only two hints remain: One with a TODO, and one for default window size
which isn't used. I wasn't sure what to do about those, so I left them
for now.
> Fix hints and lints.

- lib/src/streams/stream_handler.dart
- lib/transport.dart
- pubspec.yaml
- test/transport_test.dart
Normally, a stream RST is delivered as an error on the incoming stream,
but if the incoming stream has already been consumed, there is no good
way to detect that the stream has been terminated.
Added a `onTerminated` hook, allowing user code to register a callback that
is invoked when a RST frame is received. The gRPC code uses this to
detect when a call has been canceled.
> Add hook for receiving stream RST error.

- CHANGELOG.md
- lib/src/connection_preface.dart
- lib/src/flowcontrol/window.dart
- lib/src/flowcontrol/window_handler.dart
- test/src/flowcontrol/window_handler_test.dart
Make sure the positiveWindow is marked un-buffered if the window opens
due to an increase in initial window size. Otherwise, even sub-sequent
WindowUpdate frames wouldn't cause a bufferEmpty event to get emitted.
Also, if the connection preface doesn't match, don't try to add data to
the terminated connection.
> Window updates.

- CHANGELOG.md
- lib/src/connection.dart
- lib/src/streams/stream_handler.dart
- lib/transport.dart
- pubspec.yaml
- test/transport_test.dart
The callback is invoked whenever the number of active streams drops to 0.
This can be used to implement an idle connection timeout.
> Add onIdle callback to Connection.

- CHANGELOG.md
- lib/src/connection.dart
- lib/src/streams/stream_handler.dart
- lib/transport.dart
- pubspec.yaml
The new syntax isn't fully supported in 1.24, so switching back to good
old typedef.
Fixes #14.
> Remove use of new Function syntax for onActiveStateChanged.

- pubspec.yaml
Mockito v2.2.0 has a SDK constraint that isn't compatible with bleeding edge Dart SDK. v2.0.0 looks fine, and we don't depend on anything new from 2.2.0 anyway.
> Lower mockito dependency to 2.0.0

- lib/src/artificial_server_socket.dart
- lib/transport.dart
Preparation for upcoming changes to Stream in Dart 2.0. Instead of
having our own mixin implementing the Stream interface, let's just use
the provided StreamView wrapper.
> Use StreamView instead of StreamMethodsMixin.

- test/client_test.dart
- test/server_test.dart
- test/src/streams/helper.dart
- test/transport_test.dart
Add void declarations to methods with implicit dynamic returning void
values, which may be illegal in dart 2, but in either case, expresses
the current intent better.
> Changes for landing https://github.com/dart-lang/sdk/issues/32161

- lib/src/connection.dart
- lib/src/flowcontrol/connection_queues.dart
- lib/src/flowcontrol/queue_messages.dart
#29 appears to be caused by a race condition where calling finish() will immediately write a GOAWAY frame to the framewriter which can cause queued messages to be sent after the GOAWAY.
This PR fixes this issue by queuing the GOAWAYs as well, giving the queued up message a chance to clear our in order.
Tested:
dart --sync-async test/transport_test.dart
> Fixes #29 by queuing GOAWAY messages

- README.md
- example/display_headers.dart
- lib/transport.dart
The example in the dart-doc was already obsolete, so I replaced it with a reference to the code example.
In the README there is now a simplified version of the example.
This fixes: https://github.com/dart-lang/http2/issues/2
> Fill in README.md.

- test/multiprotocol_server_test.dart
An upcoming change to the Dart SDK will change `HttpRequest` and
`HttpClientResponse` from implementing `Stream<List<int>>` to
implementing `Stream<Uint8List>`.
This forwards-compatible change prepares for that SDK breaking
change by casting the Stream to `List<int>` before transforming
it.
https://github.com/dart-lang/sdk/issues/36900
> Prepare for upcoming change to HttpRequest and HttpClientResponse

- analysis_options.yaml
- experimental/server.dart
- pubspec.yaml
- test/client_test.dart
- test/client_websites_test.dart
- test/src/connection_preface_test.dart
- test/src/ping/ping_handler_test.dart
- test/src/streams/simple_push_test.dart
- test/src/streams/streams_test.dart
- test/transport_test.dart
This lint typically highlights async bugs. In this case the violations
were all in tests so it is relatively safe to ignore them all (with
`unawaited`) for now as the least disruptive change.
- Add a dev dependency on `pedantic`.
- Use `unawaited` to mask all lints in tests.
> Enable lint unawaited_futures

- .travis.yml
- analysis_options.yaml
- lib/multiprotocol_server.dart
- lib/src/flowcontrol/connection_queues.dart
- lib/src/frames/frame_reader.dart
- lib/src/hpack/huffman.dart
- lib/src/streams/stream_handler.dart
- lib/transport.dart
- pubspec.yaml
- test/src/frames/frame_writer_reader_test.dart
Fix the remaining new lints:
- curly_braces_in_flow_control_structures
- prefer_collection_literals
- prefer_conditional_assignment
- prefer_spread_collections
- unnecessary_this
Remove the manually specified lints that overlap with pedantic.
Bump to a more recent SDK to support enhanced collection literals.
> Enable package:pedantic lints

- test/src/flowcontrol/stream_queues_test.dart
- test/src/frames/frame_reader_test.dart
- test/src/frames/frame_writer_reader_test.dart
- test/src/hpack/hpack_test.dart
- test/src/streams/simple_push_test.dart
The failure message for specific matchers is nicer than comparing ints.
Find places using `expression.length` as the actual and a number as the
expected, and rewrite with the `hasLength` matcher.
> Use hasLength in tests

- analysis_options.yaml
- test/client_test.dart
- test/multiprotocol_server_test.dart
- test/src/flowcontrol/connection_queues_test.dart
- test/src/flowcontrol/stream_queues_test.dart
- test/src/flowcontrol/window_handler_test.dart
- test/src/frames/frame_defragmenter_test.dart
- test/src/frames/frame_reader_test.dart
- test/src/frames/frame_writer_reader_test.dart
- test/src/ping/ping_handler_test.dart
- test/src/settings/settings_handler_test.dart
- test/src/streams/streams_test.dart
- test/transport_test.dart
Makes the places where a cast error could happen more explicit.
In many places remove the explicit `dynamic` from variable declarations
to avoid throwing away type information that is valid.
> Disable implicit casts

- test/client_test.dart
- test/multiprotocol_server_test.dart
- test/server_test.dart
- test/src/flowcontrol/stream_queues_test.dart
- test/src/frames/frame_reader_test.dart
- test/src/streams/simple_flow_test.dart
- test/src/streams/simple_push_test.dart
- test/src/streams/streams_test.dart
- test/transport_test.dart
The failure output is nicer when using a TypeMatcher over using an `is`
check and comparing against the boolean `true`.
> Use isA type matcher in tests

- lib/src/connection.dart
Adding the same behavior on either a success or error completion can be
simplified.
> Use whenComplete over then with catchError

- CHANGELOG.md
- lib/src/connection.dart
- lib/transport.dart
- test/client_test.dart
This allows to detect when settings frame was received from the server
thus avoiding any sort of hacks with artificial delays that clients 
were previously resorting to.
This does of course resolve a general problem of potential races
between server updating settings and client starting to honor them.
> Add TransportConnection.onInitialPeerSettingsReceived

- .travis.yml
- CHANGELOG.md
- experimental/server.dart
- pubspec.yaml
runZoned `onError` is deprecated. Moved to `runZonedGuarded ` which was introduced in 2.8
> Fix deprecated API usage, bump minimum SDK

- lib/src/hpack/huffman.dart
`BytesBuilder` is defined in `dart:typed_data` but currently `dart:io` is imported to import the mentioned class.
This is causing the package not working/supporting web and js platforms.
From this link https://pub.dev/packages/http2/score:
10/20 points: Supports 1 of 2 possible platforms (native, js)
Consider supporting multiple platforms:
Package not compatible with runtime js
Because:
- package:http2/http2.dart that imports:
- package:http2/transport.dart that imports:
- package:http2/src/hpack/hpack.dart that imports:
- package:http2/src/hpack/huffman_table.dart that imports:
- package:http2/src/hpack/huffman.dart that imports:
- dart:io
> Ditch dart:io import for dart:typed_data

- pubspec.yaml
Flutter 2.0 is out for a while now and we can switch to stable null-safety.
> Migrate to null-safety stable.

- lib/multiprotocol_server.dart
Use a for loop element in a list literal to collect all the futures
rather than a nested `Future.wait` to concatenate the single server
close with many connection closes.
Refactor from `return` to `=>` at both levels since this reads more
nicely if it looks declarative.
> Simplify waiting during close

- lib/src/async_utils/async_utils.dart
- lib/src/hpack/hpack.dart
> Fix hint related to importing BytesBuilder from dart:io

- CHANGELOG.md
- lib/src/flowcontrol/connection_queues.dart
- lib/src/streams/stream_handler.dart
- test/client_test.dart
- test/server_test.dart
- test/src/flowcontrol/connection_queues_test.dart
Fixes https://github.com/grpc/grpc-dart/issues/624 and #97.
Until now, closed streams generally did not respond to `DATA` frames, which could lead to a mismatch between the window size for client and server on the connection. This is fixed by sending `WINDOW_UPDATE` on receiving such data. I believe this is in line with the spec; but I may be wrong. If sending a `WINDOW_UPDATE` is not allowed, then the client should at least factor in the sent data into the connection window size, and check that the connection is large enough when requesting data on other streams.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should …
> Send WINDOW_UPDATE frames for data on closed streams.

- CHANGELOG.md
- lib/src/connection.dart
- lib/src/ping/ping_handler.dart
- lib/transport.dart
- test/src/ping/ping_handler_test.dart
To make https://github.com/grpc/grpc-dart/pull/634 possible, expose to the connection whenever a ping is received.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding …
> Expose pings to connection

- CHANGELOG.md
- pubspec.yaml
Topics help users on pub.dev discover packages, and related packages.
You can see a list of [topics here](https://pub.dev/topics).
You can also make your own topics.
Topics are added to pubspec.yaml as follows:
```
topics:
- my-topic
- some-other-topic
```
See also: https://dart.dev/tools/pub/pubspec#topics
> Add `topics` to package "http2" `pubspec.yaml`
